AC=input("Enter Account Number: ")
ACName=input("Enter Account Holder Name: ")
BankName=input("Enter Bank Name: ")
Branch=input("Enter Branch Name: ")
Balance=int(input("Enter Account Balance: "))
print("Account Number:", AC)
print("Account Holder Name:", ACName)
print("Bank Name:", BankName)
print("Branch Name:", Branch)
print("Account Balance:", Balance)  