CarN=input("Enter Car Name: ")
CarM=input("Enter Car Model: ")
Company=input("Enter Company Name: ")
Price=int(input("Enter Car Price: "))
Color=input("Enter Car Color: ")
print("================================")
print("Car Name:", CarN)
print("Car Model:", CarM)
print("Company Name:", Company)
print("Car Price:", Price)
print("Car Color:", Color)
print("================================")