BookID=input("Enter Book ID: ")
bookName=input("Enter Book Name: ")
authorName=input("Enter Author Name: ")
price=input("Enter Price: ")
publisher=input("Enter Publisher: ")
print("Book ID: ", BookID)
print("Book Name: ", bookName)
print("Author Name: ", authorName)
print("Price: ", price)
print("Publisher: ", publisher)
