studentname = input("Enter your name: ")
Fathername = input("Enter your father's name: ")
course = input("Enter your course: ")
email = input("Enter your email: ")
mobilenumber = input("Enter your mobile number: ")
print("Student Name: ", studentname)
print("Father's Name: ", Fathername)
print("Course: ", course)
print("Email: ", email)
print("Mobile Number: ", mobilenumber)