EmpID=input("Enter employee ID: ")
EmpName=input("Enter employee name: ")
EmpDept=input("Enter employee department: ")
city=input("Enter employee city: ")
EmpSal=input("Enter employee salary: ")
print("Employee ID: ",EmpID)
print("Employee Name: ",EmpName)
print("Employee Department: ",EmpDept)
print("Employee City: ",city)
print("Employee Salary: ",EmpSal)