Name=input("Enter your name: ")
age=input("Enter your age: ")
G=input("Enter your gender: ")
M=input("Enter your mobile number: ")
city=input("Enter your city: ")
print("Name: ",Name)
print("Age: ",age)
print("Gender: ",G)
print("Mobile Number: ",M)
print("City: ",city)