St=input("Enter student name: ")
Rn=input("Enter roll number: ")
Co=input("Enter course name: ")
Ag=input("Enter age: ")
Pe=input("Enter percentage: ")
print("Student Name: ",St)
print("Roll Number: ",Rn)
print("Course Name: ",Co)
print("Age: ",Ag)
print("Percentage: ",Pe)
